# ================================
# Site Settings
# ================================
title: "AI Tools for Small Business"
email: contact@nakadpixel.com
description: >-
  Discover how AI tools can transform your small business operations.
  Expert reviews, implementation guides, and case studies on artificial intelligence
  for entrepreneurs and business owners.
baseurl: "/AI-Tools-for-Small-Business"
url: "https://nakad-pixel.github.io"
twitter_username: nakad_pixel
github_username: nakad-pixel

# ================================
# Build Settings
# ================================
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# ================================
# Collections
# ================================
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# ================================
# Defaults
# ================================
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Assistant"
      image: "/assets/default-post-image.jpg"
      comments: true
      seo:
        type: BlogPosting

# ================================
# SEO & Social
# ================================
twitter:
  username: nakad_pixel
  card: summary_large_image

social:
  name: "Nakad Pixel"
  links:
    - https://twitter.com/nakad_pixel
    - https://github.com/nakad-pixel

# ================================
# Analytics
# ================================
google_analytics: G-1234567890   # Replace with your real Google Analytics ID

# ================================
# AdSense
# ================================
adsense:
  client: ca-pub-1234567890123456  # Replace with your AdSense Client ID
  slot: 1234567890                 # Replace with your AdSense Slot ID

# ================================
# RSS
# ================================
feed:
  path: atom.xml

# ================================
# Disqus Comments
# ================================
disqus:
  shortname: nakad-pixel-blog   # Replace with your real Disqus shortname
